### ISSUE TITLE
Upload the visualised Schema to gh-pages/Heroku

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-json-schema#10]
**How** to use JSON schema visualiser and push up your visualised schema to GH-pages

**Comment by sohilpandya** [comment]
GH-pages branch does not work with DWYL organisation as it keeps on redirecting me to www.dwyl.io/path/to/file rather than dwyl.github.io/path/to/file
😞

**Comment by iteles** [comment]
@sohilpandya Pretty sure that's because I have a redirect set-up somewhere even though we never actually used gh-pages for our site (I toyed with the idea originally - see name of our website repo https://github.com/dwyl/dwyl.github.io) . Let me look into it tonight.

**Comment by sohilpandya** [comment]
I was unable to get the schema working with dwyl gh-pages, I've done some research and it looks like it won't be possible to have a gh-pages branch working due to the CNAME redirection we have in place. All repos will redirected to `www.dwyl.io/name/of/repo` 😟 

**Alternative** was to push it up to Heroku. Here are the steps I've taken to get it up and running on Heroku (these steps would also work for a GH-pages branch):
1. put the bundled file from #9 into a `dist` folder 
   Now we only want to push the `dist` folder up onto our gh-pages branch. For this to happen we will have to create a subtree push.
2. `git subtree push --prefix dist origin gh-pages`
   - This will only push the dist folder up to the gh-pages branch
3. Now if your organisation/username does not have a CNAME redirect, you can visit the GitHub page under `username.github.io/reponame/index.html` 🎉 

**Unfortunately** for us, we were unable to get the github pages to work. 😢 So we had to take these additional steps to get it working on Heroku
1. add a file named index.php into the `gh-branch` branch with the following code
   - `<?php header( 'Location: /index.html' ) ;  ?>`
   - All this will do is redirect all the requests to index.html 
   - We need this to be able to get the static files to work on Heroku
   - Heroku requires php/RoR/Node build packs in order to Build.
   - This one line will let Heroku build a simple server for serving our files
2. commit the additional file to the gh-branch and push it using the same subtree push method mentioned in step 2.
3. create a Heroku app
   - `heroku create`
   -  Add the Remote version using `heroku git:remote -a name-of-app`
4. push the gh-branch onto Herkou
   - `git subtree push --prefix dist heroku master`

Your app should be up and running on Heroku 🎉 

### Our Example schema is uploaded here https://whispering-hollows-54760.herokuapp.com/index.html
